on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test_and_build:
    name: Test & Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v2
      - name: ⚙️ Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: 🐧 Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: 🍏 Dependencies
        if: matrix.os == 'macos-latest'
        run: brew install automake
      - name: ⚡ Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-${{ hashFiles('**/Cargo.toml') }}
      - name: 🔎 Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: 🔨 Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    needs: test_and_build
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v2
      - name: ⚙️ Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: ⚡ Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: windows-latest-${{ hashFiles('**/Cargo.toml') }}
      - name: 🚀 Publish
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo install cargo-release
          cargo release --no-confirm --no-dev-version --skip-tag --skip-push'
